name: Docker Update Auto Merge
on:
  pull_request:
    types: [opened, edited]
  schedule:
    - cron: '0 11 * * *'
    - cron: '35 13 * * *'


permissions:
  pull-requests: write
  contents: write

jobs:
  auto_approve_and_merge:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'demisto/') && github.repository == 'Shellyber/content' && contains(github.event.pull_request.labels.*.name, 'docker')
    steps:
      - name: Approve and auto-merge for docker update PRs
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Approving and merging"
          gh pr review --approve "$PR_URL"
          gh pr merge --squash "$PR_URL"