name: Docker Update Auto Merge
on:
  pull_request:
    branches:
      - 'demisto/**'

jobs:
  output_info:
    runs-on: ubuntu-latest
    steps:
      - name: Print out event stufffff
        run: |
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}